//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionDePrueba.ServicePais {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pais", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePais.WebServicePaisSoap")]
    public interface WebServicePaisSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento retornaTodosLosPaisesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaTodosLosPaises", ReplyAction="*")]
        AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse retornaTodosLosPaises(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaTodosLosPaises", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse> retornaTodosLosPaisesAsync(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pais del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarPais", ReplyAction="*")]
        AplicacionDePrueba.ServicePais.guardarPaisResponse guardarPais(AplicacionDePrueba.ServicePais.guardarPaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarPais", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.guardarPaisResponse> guardarPaisAsync(AplicacionDePrueba.ServicePais.guardarPaisRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento posicionPaisResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionPais", ReplyAction="*")]
        AplicacionDePrueba.ServicePais.posicionPaisResponse posicionPais(AplicacionDePrueba.ServicePais.posicionPaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionPais", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.posicionPaisResponse> posicionPaisAsync(AplicacionDePrueba.ServicePais.posicionPaisRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento buscaPaisResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaPais", ReplyAction="*")]
        AplicacionDePrueba.ServicePais.buscaPaisResponse buscaPais(AplicacionDePrueba.ServicePais.buscaPaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaPais", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.buscaPaisResponse> buscaPaisAsync(AplicacionDePrueba.ServicePais.buscaPaisRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pais del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizaPais", ReplyAction="*")]
        AplicacionDePrueba.ServicePais.actualizaPaisResponse actualizaPais(AplicacionDePrueba.ServicePais.actualizaPaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizaPais", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.actualizaPaisResponse> actualizaPaisAsync(AplicacionDePrueba.ServicePais.actualizaPaisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaPais", ReplyAction="*")]
        bool eliminaPais(int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaPais", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminaPaisAsync(int idPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/esActivo", ReplyAction="*")]
        bool esActivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/esActivo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> esActivoAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retornaTodosLosPaisesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retornaTodosLosPaises", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequestBody Body;
        
        public retornaTodosLosPaisesRequest() {
        }
        
        public retornaTodosLosPaisesRequest(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class retornaTodosLosPaisesRequestBody {
        
        public retornaTodosLosPaisesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retornaTodosLosPaisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retornaTodosLosPaisesResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponseBody Body;
        
        public retornaTodosLosPaisesResponse() {
        }
        
        public retornaTodosLosPaisesResponse(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retornaTodosLosPaisesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionDePrueba.ServicePais.ArrayOfAnyType retornaTodosLosPaisesResult;
        
        public retornaTodosLosPaisesResponseBody() {
        }
        
        public retornaTodosLosPaisesResponseBody(AplicacionDePrueba.ServicePais.ArrayOfAnyType retornaTodosLosPaisesResult) {
            this.retornaTodosLosPaisesResult = retornaTodosLosPaisesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarPaisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarPais", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.guardarPaisRequestBody Body;
        
        public guardarPaisRequest() {
        }
        
        public guardarPaisRequest(AplicacionDePrueba.ServicePais.guardarPaisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarPaisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionDePrueba.ServicePais.Pais pais;
        
        public guardarPaisRequestBody() {
        }
        
        public guardarPaisRequestBody(AplicacionDePrueba.ServicePais.Pais pais) {
            this.pais = pais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarPaisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarPaisResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.guardarPaisResponseBody Body;
        
        public guardarPaisResponse() {
        }
        
        public guardarPaisResponse(AplicacionDePrueba.ServicePais.guardarPaisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarPaisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool guardarPaisResult;
        
        public guardarPaisResponseBody() {
        }
        
        public guardarPaisResponseBody(bool guardarPaisResult) {
            this.guardarPaisResult = guardarPaisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class posicionPaisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="posicionPais", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.posicionPaisRequestBody Body;
        
        public posicionPaisRequest() {
        }
        
        public posicionPaisRequest(AplicacionDePrueba.ServicePais.posicionPaisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class posicionPaisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int posicion;
        
        public posicionPaisRequestBody() {
        }
        
        public posicionPaisRequestBody(int posicion) {
            this.posicion = posicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class posicionPaisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="posicionPaisResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.posicionPaisResponseBody Body;
        
        public posicionPaisResponse() {
        }
        
        public posicionPaisResponse(AplicacionDePrueba.ServicePais.posicionPaisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class posicionPaisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionDePrueba.ServicePais.Pais posicionPaisResult;
        
        public posicionPaisResponseBody() {
        }
        
        public posicionPaisResponseBody(AplicacionDePrueba.ServicePais.Pais posicionPaisResult) {
            this.posicionPaisResult = posicionPaisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscaPaisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscaPais", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.buscaPaisRequestBody Body;
        
        public buscaPaisRequest() {
        }
        
        public buscaPaisRequest(AplicacionDePrueba.ServicePais.buscaPaisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscaPaisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPais;
        
        public buscaPaisRequestBody() {
        }
        
        public buscaPaisRequestBody(int idPais) {
            this.idPais = idPais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscaPaisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscaPaisResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.buscaPaisResponseBody Body;
        
        public buscaPaisResponse() {
        }
        
        public buscaPaisResponse(AplicacionDePrueba.ServicePais.buscaPaisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscaPaisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionDePrueba.ServicePais.Pais buscaPaisResult;
        
        public buscaPaisResponseBody() {
        }
        
        public buscaPaisResponseBody(AplicacionDePrueba.ServicePais.Pais buscaPaisResult) {
            this.buscaPaisResult = buscaPaisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizaPaisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizaPais", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.actualizaPaisRequestBody Body;
        
        public actualizaPaisRequest() {
        }
        
        public actualizaPaisRequest(AplicacionDePrueba.ServicePais.actualizaPaisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizaPaisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionDePrueba.ServicePais.Pais pais;
        
        public actualizaPaisRequestBody() {
        }
        
        public actualizaPaisRequestBody(AplicacionDePrueba.ServicePais.Pais pais) {
            this.pais = pais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizaPaisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizaPaisResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionDePrueba.ServicePais.actualizaPaisResponseBody Body;
        
        public actualizaPaisResponse() {
        }
        
        public actualizaPaisResponse(AplicacionDePrueba.ServicePais.actualizaPaisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizaPaisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizaPaisResult;
        
        public actualizaPaisResponseBody() {
        }
        
        public actualizaPaisResponseBody(bool actualizaPaisResult) {
            this.actualizaPaisResult = actualizaPaisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePaisSoapChannel : AplicacionDePrueba.ServicePais.WebServicePaisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePaisSoapClient : System.ServiceModel.ClientBase<AplicacionDePrueba.ServicePais.WebServicePaisSoap>, AplicacionDePrueba.ServicePais.WebServicePaisSoap {
        
        public WebServicePaisSoapClient() {
        }
        
        public WebServicePaisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePaisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePaisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePaisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse AplicacionDePrueba.ServicePais.WebServicePaisSoap.retornaTodosLosPaises(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest request) {
            return base.Channel.retornaTodosLosPaises(request);
        }
        
        public AplicacionDePrueba.ServicePais.ArrayOfAnyType retornaTodosLosPaises() {
            AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest inValue = new AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequestBody();
            AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse retVal = ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).retornaTodosLosPaises(inValue);
            return retVal.Body.retornaTodosLosPaisesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse> AplicacionDePrueba.ServicePais.WebServicePaisSoap.retornaTodosLosPaisesAsync(AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest request) {
            return base.Channel.retornaTodosLosPaisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.retornaTodosLosPaisesResponse> retornaTodosLosPaisesAsync() {
            AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest inValue = new AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.retornaTodosLosPaisesRequestBody();
            return ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).retornaTodosLosPaisesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionDePrueba.ServicePais.guardarPaisResponse AplicacionDePrueba.ServicePais.WebServicePaisSoap.guardarPais(AplicacionDePrueba.ServicePais.guardarPaisRequest request) {
            return base.Channel.guardarPais(request);
        }
        
        public bool guardarPais(AplicacionDePrueba.ServicePais.Pais pais) {
            AplicacionDePrueba.ServicePais.guardarPaisRequest inValue = new AplicacionDePrueba.ServicePais.guardarPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.guardarPaisRequestBody();
            inValue.Body.pais = pais;
            AplicacionDePrueba.ServicePais.guardarPaisResponse retVal = ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).guardarPais(inValue);
            return retVal.Body.guardarPaisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.guardarPaisResponse> AplicacionDePrueba.ServicePais.WebServicePaisSoap.guardarPaisAsync(AplicacionDePrueba.ServicePais.guardarPaisRequest request) {
            return base.Channel.guardarPaisAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.guardarPaisResponse> guardarPaisAsync(AplicacionDePrueba.ServicePais.Pais pais) {
            AplicacionDePrueba.ServicePais.guardarPaisRequest inValue = new AplicacionDePrueba.ServicePais.guardarPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.guardarPaisRequestBody();
            inValue.Body.pais = pais;
            return ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).guardarPaisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionDePrueba.ServicePais.posicionPaisResponse AplicacionDePrueba.ServicePais.WebServicePaisSoap.posicionPais(AplicacionDePrueba.ServicePais.posicionPaisRequest request) {
            return base.Channel.posicionPais(request);
        }
        
        public AplicacionDePrueba.ServicePais.Pais posicionPais(int posicion) {
            AplicacionDePrueba.ServicePais.posicionPaisRequest inValue = new AplicacionDePrueba.ServicePais.posicionPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.posicionPaisRequestBody();
            inValue.Body.posicion = posicion;
            AplicacionDePrueba.ServicePais.posicionPaisResponse retVal = ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).posicionPais(inValue);
            return retVal.Body.posicionPaisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.posicionPaisResponse> AplicacionDePrueba.ServicePais.WebServicePaisSoap.posicionPaisAsync(AplicacionDePrueba.ServicePais.posicionPaisRequest request) {
            return base.Channel.posicionPaisAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.posicionPaisResponse> posicionPaisAsync(int posicion) {
            AplicacionDePrueba.ServicePais.posicionPaisRequest inValue = new AplicacionDePrueba.ServicePais.posicionPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.posicionPaisRequestBody();
            inValue.Body.posicion = posicion;
            return ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).posicionPaisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionDePrueba.ServicePais.buscaPaisResponse AplicacionDePrueba.ServicePais.WebServicePaisSoap.buscaPais(AplicacionDePrueba.ServicePais.buscaPaisRequest request) {
            return base.Channel.buscaPais(request);
        }
        
        public AplicacionDePrueba.ServicePais.Pais buscaPais(int idPais) {
            AplicacionDePrueba.ServicePais.buscaPaisRequest inValue = new AplicacionDePrueba.ServicePais.buscaPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.buscaPaisRequestBody();
            inValue.Body.idPais = idPais;
            AplicacionDePrueba.ServicePais.buscaPaisResponse retVal = ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).buscaPais(inValue);
            return retVal.Body.buscaPaisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.buscaPaisResponse> AplicacionDePrueba.ServicePais.WebServicePaisSoap.buscaPaisAsync(AplicacionDePrueba.ServicePais.buscaPaisRequest request) {
            return base.Channel.buscaPaisAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.buscaPaisResponse> buscaPaisAsync(int idPais) {
            AplicacionDePrueba.ServicePais.buscaPaisRequest inValue = new AplicacionDePrueba.ServicePais.buscaPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.buscaPaisRequestBody();
            inValue.Body.idPais = idPais;
            return ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).buscaPaisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionDePrueba.ServicePais.actualizaPaisResponse AplicacionDePrueba.ServicePais.WebServicePaisSoap.actualizaPais(AplicacionDePrueba.ServicePais.actualizaPaisRequest request) {
            return base.Channel.actualizaPais(request);
        }
        
        public bool actualizaPais(AplicacionDePrueba.ServicePais.Pais pais) {
            AplicacionDePrueba.ServicePais.actualizaPaisRequest inValue = new AplicacionDePrueba.ServicePais.actualizaPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.actualizaPaisRequestBody();
            inValue.Body.pais = pais;
            AplicacionDePrueba.ServicePais.actualizaPaisResponse retVal = ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).actualizaPais(inValue);
            return retVal.Body.actualizaPaisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.actualizaPaisResponse> AplicacionDePrueba.ServicePais.WebServicePaisSoap.actualizaPaisAsync(AplicacionDePrueba.ServicePais.actualizaPaisRequest request) {
            return base.Channel.actualizaPaisAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionDePrueba.ServicePais.actualizaPaisResponse> actualizaPaisAsync(AplicacionDePrueba.ServicePais.Pais pais) {
            AplicacionDePrueba.ServicePais.actualizaPaisRequest inValue = new AplicacionDePrueba.ServicePais.actualizaPaisRequest();
            inValue.Body = new AplicacionDePrueba.ServicePais.actualizaPaisRequestBody();
            inValue.Body.pais = pais;
            return ((AplicacionDePrueba.ServicePais.WebServicePaisSoap)(this)).actualizaPaisAsync(inValue);
        }
        
        public bool eliminaPais(int idPais) {
            return base.Channel.eliminaPais(idPais);
        }
        
        public System.Threading.Tasks.Task<bool> eliminaPaisAsync(int idPais) {
            return base.Channel.eliminaPaisAsync(idPais);
        }
        
        public bool esActivo() {
            return base.Channel.esActivo();
        }
        
        public System.Threading.Tasks.Task<bool> esActivoAsync() {
            return base.Channel.esActivoAsync();
        }
    }
}
